### ISSUE TITLE
ebtables addition

### ISSUE THREAD

**Issue by evan-shaw** [arno-iptables-firewall/aif#52]
Not an issue, more of a request, if you think possible.
My PC that I use as my gateway server, with arno firewall installed also acts as my dhcp server. I use mac address filtering, so I know what devices can go through the firewall on the clean side. However I can't stop anyone not in the mac-address list from getting an IP address in the first place. Apparently dhcp is at a lower level than ip, so the firewall doesn't block the request for an ip address. But I think ebtables could solve that issue, e.g. ebtables -A INPUT -s xx:xx:xx:xx:xx:xx -j DROP 

Is this something you could think about adding?

**Comment by abelbeck** [comment]
Perhaps the current mac-address-filter plugin would work for you ?

Basically create a MAC_ADDRESS_FILE specified white-list file of MAC addresses.

**Comment by evan-shaw** [comment]
Hi abelbeck, no I'm already doing the mac-address filtering using the plugin method you describe, but it doesn't block dhcp requests, which are at a lower network layer.

**Comment by abelbeck** [comment]
DHCP uses UDP, not a lower network layer, but it does use a 255.255.255.255 broadcast address.  It looks like your client's DHCPDISCOVER is allowed regardless of MAC address in the mac-address-filter plugin (by design) with the rule:
```
ip4tables -A MAC_FILTER -d 255.255.255.255 -j RETURN
```
You could try commenting out that rule in `plugins/10mac-address-filter.plugin` and see if that gives the behavior you want.

**Comment by abelbeck** [comment]
Look for `/usr/share/arno-iptables-firewall/plugins/10mac-address-filter.plugin` or similar.

**Comment by arnova** [comment]
I think this can be closed, if not please reopen.
